// @ts-check
import { defineConfig } from 'astro/config';
import vercel from '@astrojs/vercel';

import { SITE_URL } from './src/config/site.mjs';

/**
 * The migrated WordPress site served every canonical URL with a trailing
 * slash, so that behaviour is preserved exactly.
 *
 * The sitemap is generated by src/pages/sitemap.xml.ts rather than
 * @astrojs/sitemap, because it has to live at exactly /sitemap.xml - the path
 * the old robots.txt advertised - and list only canonical indexable URLs.
 */
export default defineConfig({
  site: SITE_URL,
  trailingSlash: 'always',
  output: 'static',
  adapter: vercel({
    imageService: false,
    webAnalytics: { enabled: false },
  }),
  build: {
    format: 'directory',
    inlineStylesheets: 'auto',
  },
  /*
   * Astro inlines small script and style chunks, which a `script-src 'self'`
   * policy would block. Letting Astro own the CSP means it emits SHA-256
   * hashes for exactly what it inlined, so the policy stays strict with no
   * 'unsafe-inline'. vercel.json keeps the header-only directives (CSP in a
   * <meta> tag cannot express frame-ancestors).
   */
  security: {
    csp: {
      algorithm: 'SHA-256',
      directives: [
        "default-src 'self'",
        "base-uri 'self'",
        "object-src 'none'",
        "form-action 'self'",
        "img-src 'self' data:",
        "font-src 'self'",
        "connect-src 'self'",
        "manifest-src 'self'",
        'upgrade-insecure-requests',
      ],
      scriptDirective: { resources: ["'self'"] },
      styleDirective: { resources: ["'self'"] },
    },
  },
  /*
   * WooCommerce checkout URLs that have no equivalent in the quotation model.
   * The quote page is the genuine replacement for both, so these are the only
   * 301s the migration introduces; every other old URL is unchanged and 200s.
   */
  redirects: {
    '/cart': { status: 301, destination: '/get-quote/' },
    '/checkout': { status: 301, destination: '/get-quote/' },
  },
  vite: {
    build: { assetsInlineLimit: 1024 },
  },
});
