// @ts-check
import { defineConfig } from 'astro/config';
import vercel from '@astrojs/vercel';

import { SITE_URL } from './src/config/site.mjs';

/**
 * The migrated WordPress site served every canonical URL with a trailing
 * slash, so that behaviour is preserved exactly.
 *
 * The sitemap is generated by src/pages/sitemap.xml.ts rather than
 * @astrojs/sitemap, because it has to live at exactly /sitemap.xml - the path
 * the old robots.txt advertised - and list only canonical indexable URLs.
 */
export default defineConfig({
  site: SITE_URL,
  trailingSlash: 'always',
  output: 'static',
  adapter: vercel({
    imageService: false,
    webAnalytics: { enabled: false },
  }),
  build: {
    format: 'directory',
    inlineStylesheets: 'auto',
  },
  /*
   * The retired WooCommerce URLs (/cart/, /checkout/) are redirected in
   * vercel.json rather than here: the adapter compiles Astro's `redirects`
   * to `^/cart$`, which never matches the trailing-slash URL the old site
   * actually served.
   */
  /*
   * Astro inlines small script and style chunks, which a `script-src 'self'`
   * policy would block. Letting Astro own the CSP means it emits SHA-256
   * hashes for exactly what it inlined, so the policy stays strict with no
   * 'unsafe-inline'. vercel.json keeps the header-only directives (CSP in a
   * <meta> tag cannot express frame-ancestors).
   */
  security: {
    csp: {
      algorithm: 'SHA-256',
      directives: [
        "default-src 'self'",
        "base-uri 'self'",
        "object-src 'none'",
        "form-action 'self'",
        "img-src 'self' data: https://chat.zeeops.dev",
        "font-src 'self'",
        "connect-src 'self' https://chat.zeeops.dev wss://chat.zeeops.dev",
        "manifest-src 'self'",
        'upgrade-insecure-requests',
      ],
      scriptDirective: { resources: ["'self'", 'https://chat.zeeops.dev'] },
      styleDirective: { resources: ["'self'"] },
    },
  },
  vite: {
    build: { assetsInlineLimit: 1024 },
  },
});
