#!/usr/bin/env python3
"""Pull the visible accordion FAQs out of the migrated components.

FAQPage schema must mirror what a visitor can actually read, so the questions
and answers are read back from the rendered components rather than re-typed.
"""
import json, os, re

# Resolved relative to this file so the tool works from any checkout.
PROJ = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))



SOURCES = {
    'homeFaqs': 'src/components/home/HomeFaq.astro',
    'productPageFaqs': 'src/components/product/ProductFaqSection.astro',
    'faqPageFaqs': 'src/components/pages/FaqContent.astro',
}


def text(s):
    s = re.sub(r'<[^>]+>', ' ', s)
    s = re.sub(r'&nbsp;', ' ', s)
    return re.sub(r'\s+', ' ', s).strip()


def inner_html(s):
    s = re.sub(r'\s+', ' ', s)
    return s.strip()


def extract(path):
    """Split on FAQ item boundaries, then read the question and answer inside."""
    s = open(os.path.join(PROJ, path), encoding='utf-8').read()
    blocks = re.split(r'<div class="hdt-faq-item"[^>]*>', s)[1:]
    items = []
    for block in blocks:
        q = re.search(r'class="hdt-faq-question"[^>]*>(.*?)</button>', block, re.S)
        a = re.search(r'class="hdt-faq-answer-content"[^>]*>(.*)', block, re.S)
        if not q or not a:
            continue
        # drop the toggle glyph that sits beside the question text
        question = text(re.sub(r'<span class="hdt-faq-(?:toggle|icon)".*?</span>', '',
                               q.group(1), flags=re.S))
        # the answer runs until its wrapper divs close
        answer = a.group(1)
        depth, end = 1, len(answer)
        for m in re.finditer(r'<div\b|</div>', answer):
            depth += 1 if m.group(0) == '<div' else -1
            if depth == 0:
                end = m.start()
                break
        answer = inner_html(answer[:end])
        if question and text(answer):
            items.append({'question': question, 'answer': answer})
    return items


def main():
    out = {}
    for key, path in SOURCES.items():
        out[key] = extract(path)
        print(f'{key}: {len(out[key])} FAQs')
        for f in out[key][:3]:
            print('   -', f['question'][:70])

    ts = ['/**',
          ' * FAQ content that is visibly rendered by the migrated accordion',
          ' * components, mirrored here so FAQPage schema can never drift from the page.',
          ' *',
          ' * Generated by tools/extract_page_faqs.py - do not edit by hand.',
          ' */',
          "import type { ProductFaq } from './products';",
          '']
    for key, items in out.items():
        ts.append(f'export const {key}: ProductFaq[] = ' +
                  json.dumps(items, ensure_ascii=False, indent=2) + ';')
        ts.append('')
    open(os.path.join(PROJ, 'src/data/page-faqs.ts'), 'w', encoding='utf-8').write('\n'.join(ts))


if __name__ == '__main__':
    main()
