/**
 * FAQ content that is visibly rendered by the migrated accordion
 * components, mirrored here so FAQPage schema can never drift from the page.
 *
 * Generated by tools/extract_page_faqs.py - do not edit by hand.
 */
import type { ProductFaq } from './products';

export const homeFaqs: ProductFaq[] = [
  {
    "question": "What is the minimum order quantity?",
    "answer": "<p>Our minimum order quantity starts at <strong>100 units</strong>. This allows us to maintain competitive wholesale pricing while ensuring quality production. We also offer significant bulk discounts for larger orders:</p> <ul> <li>100-500 units: Standard pricing</li> <li>500-1,000 units: 5% discount</li> <li>1,000-5,000 units: 10% discount</li> <li>5,000+ units: 15% discount</li> </ul>"
  },
  {
    "question": "How long does production and delivery take?",
    "answer": "<p><strong>Standard production time is 7-10 business days</strong> after design approval. Shipping times vary by location:</p> <ul> <li><strong>USA:</strong> 3-5 business days</li> <li><strong>Canada:</strong> 3-5 business days</li> <li><strong>UK:</strong> 5-7 business days</li> <li><strong>Australia:</strong> 7-10 business days</li> <li><strong>Europe:</strong> 5-7 business days</li> </ul> <p>Rush production options are available for an additional fee if you need your order faster.</p>"
  },
  {
    "question": "Do you offer custom printing and design services?",
    "answer": "<p><strong>Yes! We offer completely free design services</strong> with every order. Our expert design team will create custom artwork featuring your logo, brand colors, and messaging at no additional cost.</p> <p>We offer:</p> <ul> <li>Full-color CMYK printing</li> <li>Custom sizes and shapes</li> <li>Multiple coating options (matte, gloss, spot UV)</li> <li>Up to 3 free design revisions</li> </ul> <p>You can also provide your own design files in PDF, AI, EPS, or PSD format.</p>"
  },
  {
    "question": "What materials are your hot dog trays made from?",
    "answer": "<p>We offer hot dog trays in several premium materials:</p> <ul> <li><strong>Kraft Paper:</strong> Eco-friendly, recyclable, natural brown finish</li> <li><strong>White Cardboard:</strong> Smooth surface, perfect for vibrant color printing</li> <li><strong>Corrugated:</strong> Extra-thick with superior insulation and durability</li> <li><strong>Food-Safe Plastic:</strong> Reusable, durable, and easy to clean</li> </ul> <p>All materials are <strong>FDA-approved</strong>, food-grade, and safe for direct food contact.</p>"
  },
  {
    "question": "Are your hot dog trays eco-friendly?",
    "answer": "<p><strong>Yes! Environmental sustainability is important to us.</strong> We offer multiple eco-friendly options:</p> <ul> <li><strong>100% Recyclable:</strong> All paper and cardboard trays can be recycled</li> <li><strong>Biodegradable:</strong> Break down naturally without harming the environment</li> <li><strong>FSC-Certified Paper:</strong> Sourced from responsibly managed forests</li> <li><strong>Compostable Coatings:</strong> Plant-based, non-toxic finishes</li> </ul>"
  },
  {
    "question": "How much do custom hot dog trays cost?",
    "answer": "<p>Pricing starts at <strong>$0.70 per unit</strong> for bulk orders. The exact price depends on:</p> <ul> <li>Order quantity (larger orders = lower per-unit cost)</li> <li>Material type selected</li> <li>Printing requirements (full-color vs. plain)</li> <li>Special features or finishes</li> </ul> <p><strong>Request a free quote</strong> to get exact pricing for your specific needs. There are no hidden fees or setup charges.</p>"
  },
  {
    "question": "Can I order samples before placing a bulk order?",
    "answer": "<p><strong>Yes!</strong> We offer sample packs so you can feel the quality of our materials and see the printing quality before committing to a large order. Contact us at <strong>(503) 358-0443</strong> or <strong>info@hotdogtrays.com</strong> to request samples.</p> <p>Standard shipping costs apply for sample orders.</p>"
  },
  {
    "question": "What payment methods do you accept?",
    "answer": "<p>We accept all major payment methods:</p> <ul> <li>Credit cards (Visa, Mastercard, American Express, Discover)</li> <li>PayPal</li> <li>Bank transfers (ACH/Wire)</li> <li>Purchase orders for established businesses</li> </ul> <p>Payment is typically required before production begins. Net 30 terms are available for qualified businesses.</p>"
  }
];

export const productPageFaqs: ProductFaq[] = [
  {
    "question": "What is the minimum order quantity?",
    "answer": "<p>Our minimum order quantity starts at <strong>100 units</strong>. This allows us to maintain competitive wholesale pricing while ensuring quality production.</p> <div class=\"hdt-faq-highlight\"> <strong>Volume Discounts Available:</strong> </div> <ul> <li><strong>100-500 units:</strong> Standard pricing starting at $0.70/ea</li> <li><strong>500-1,000 units:</strong> 5% discount</li> <li><strong>1,000-5,000 units:</strong> 10% discount</li> <li><strong>5,000+ units:</strong> 15% discount + free shipping</li> </ul> <p>For orders above 10,000 units, please <a href=\"/contact/\">contact us</a> for special pricing.</p>"
  },
  {
    "question": "Can I get custom printing on the trays?",
    "answer": "<p><strong>Yes! We offer completely free custom printing and design services</strong> with every order. Our expert design team will create custom artwork featuring your logo, brand colors, and messaging at no additional cost.</p> <p><strong>What we offer:</strong></p> <ul> <li>Full-color CMYK printing (unlimited colors)</li> <li>Pantone color matching available</li> <li>High-resolution 300 DPI printing</li> <li>Multiple coating options (matte, gloss, spot UV)</li> <li>Inside or outside printing</li> <li>QR code integration</li> </ul> <div class=\"hdt-faq-highlight\"> <strong>FREE:</strong> Design service + Up to 3 revisions + Digital proof </div> <p>You can also provide your own design files in PDF, AI, EPS, or PSD format.</p>"
  },
  {
    "question": "What materials are available?",
    "answer": "<p>We offer hot dog trays in <strong>4 premium materials</strong>, each with unique benefits:</p> <p><strong>1. Kraft Paper (250gsm)</strong></p> <ul> <li>Natural, eco-friendly brown finish</li> <li>100% recyclable & biodegradable</li> <li>FSC-certified sustainable sourcing</li> <li>Starting at $0.70/unit</li> </ul> <p><strong>2. White Cardboard (300gsm)</strong></p> <ul> <li>Bright white finish for vibrant printing</li> <li>Excellent print quality</li> <li>Strong & rigid construction</li> <li>Starting at $0.75/unit</li> </ul> <p><strong>3. Corrugated (350gsm)</strong></p> <ul> <li>Maximum durability & strength</li> <li>Excellent heat insulation</li> <li>Prevents oil seepage</li> <li>Starting at $0.85/unit</li> </ul> <p><strong>4. Food-Safe Plastic (PP)</strong></p> <ul> <li>Reusable & dishwasher safe</li> <li>BPA-free, FDA approved</li> <li>Clear or colored options</li> <li>Starting at $0.95/unit</li> </ul> <p>All materials are <strong>FDA-approved</strong> and safe for direct food contact.</p>"
  },
  {
    "question": "How long does shipping take?",
    "answer": "<p><strong>Production time:</strong> 7-10 business days after design approval</p> <p><strong>Shipping times by location:</strong></p> <ul> <li><strong>USA:</strong> 3-5 business days</li> <li><strong>Canada:</strong> 3-5 business days</li> <li><strong>UK:</strong> 5-7 business days</li> <li><strong>Australia:</strong> 7-10 business days</li> <li><strong>Europe:</strong> 5-7 business days</li> </ul> <div class=\"hdt-faq-highlight\"> <strong>Rush Production Available:</strong> Get your order in 3-5 days for an additional fee </div> <p><strong>Free Shipping:</strong> Orders of 5,000+ units qualify for free shipping within the USA.</p> <p>All orders include real-time tracking so you can monitor your delivery every step of the way.</p>"
  },
  {
    "question": "Are samples available before I order?",
    "answer": "<p><strong>Yes! We offer sample packs</strong> so you can feel the quality of our materials and see the printing quality before committing to a large order.</p> <p><strong>Sample options:</strong></p> <ul> <li><strong>Blank Samples:</strong> FREE - Request unprinted samples in each material</li> <li><strong>Pre-Printed Samples:</strong> $25 - Samples with generic designs</li> <li><strong>Custom Sample Run:</strong> From $50 - Small batch with your design (minimum 10 units)</li> </ul> <div class=\"hdt-faq-highlight\"> <strong>Sample Credit:</strong> If you order within 30 days, we'll credit your sample cost toward your first order! </div> <p>Contact us at <a href=\"tel:5033580443\">(503) 358-0443</a> or <a href=\"mailto:info@hotdogtrays.com\">info@hotdogtrays.com</a> to request samples.</p>"
  },
  {
    "question": "What is your return policy?",
    "answer": "<p>We stand behind our products with a <strong>100% Satisfaction Guarantee</strong>.</p> <p><strong>Quality Issues:</strong></p> <ul> <li>If there are manufacturing defects or quality issues, we'll replace your order at no cost</li> <li>Claims must be made within 30 days of delivery</li> <li>Photo documentation required</li> </ul> <p><strong>Design Errors:</strong></p> <ul> <li>We require design approval before production</li> <li>If we make an error in production (not matching approved proof), we'll reprint at no charge</li> </ul> <div class=\"hdt-faq-highlight\"> <strong>Important:</strong> Custom printed products cannot be returned due to change of mind, as they are made specifically for your business. </div> <p><strong>Damaged in Transit:</strong></p> <ul> <li>Report damage within 48 hours of delivery</li> <li>We'll file a claim and send replacement items</li> </ul> <p>For full details, please review our <a href=\"/terms-conditions/\">Returns & Refunds Policy</a>.</p>"
  },
  {
    "question": "Can I order custom sizes?",
    "answer": "<p><strong>Yes! We offer fully custom sizes</strong> to fit your specific needs.</p> <p><strong>Standard sizes available:</strong></p> <ul> <li>Small: 6\" × 2\" × 1\"</li> <li>Medium: 8\" × 2.5\" × 1.5\"</li> <li>Large: 10\" × 3\" × 2\"</li> <li>Extra Large: 12\" × 3.5\" × 2.5\"</li> </ul> <p><strong>Custom sizing:</strong></p> <ul> <li>Any length from 6\" to 12\"</li> <li>Custom width and depth options</li> <li>Unique shapes and die-cuts available</li> <li>Minimum order: 500 units for fully custom sizes</li> </ul> <div class=\"hdt-faq-highlight\"> <strong>Free Size Consultation:</strong> Our team will help you determine the perfect dimensions for your product </div> <p><a href=\"/get-quote/\">Request a quote</a> with your custom size requirements.</p>"
  },
  {
    "question": "What payment methods do you accept?",
    "answer": "<p>We accept all major payment methods for your convenience:</p> <p><strong>Credit & Debit Cards:</strong></p> <ul> <li>Visa</li> <li>Mastercard</li> <li>American Express</li> <li>Discover</li> </ul> <p><strong>Digital Payments:</strong></p> <ul> <li>PayPal</li> <li>Apple Pay</li> <li>Google Pay</li> </ul> <p><strong>Business Payments:</strong></p> <ul> <li>Bank transfers (ACH/Wire)</li> <li>Purchase orders (for established businesses)</li> <li>Net 30 terms (available for qualified businesses)</li> </ul> <div class=\"hdt-faq-highlight\"> <strong>Secure Payment:</strong> All transactions are encrypted with SSL security </div> <p>Payment is typically required before production begins. For large orders or established businesses, we offer flexible payment terms.</p>"
  }
];

export const faqPageFaqs: ProductFaq[] = [
  {
    "question": "What is the minimum order quantity?",
    "answer": "<p>Our minimum order quantity starts at <strong>100 units</strong>. This allows us to maintain competitive wholesale pricing while ensuring quality production.</p> <div class=\"hdt-faq-highlight\"> <strong>Volume Discounts Available:</strong> </div> <ul> <li><strong>100-500 units:</strong> Standard pricing starting at $0.70/ea</li> <li><strong>500-1,000 units:</strong> 5% discount</li> <li><strong>1,000-5,000 units:</strong> 10% discount</li> <li><strong>5,000+ units:</strong> 15% discount + free shipping</li> </ul> <p>For orders above 10,000 units, please <a href=\"/contact/\">contact us</a> for special pricing.</p>"
  },
  {
    "question": "How do I place an order?",
    "answer": "<p>Ordering is simple! Follow these steps:</p> <ul> <li><strong>Step 1:</strong> Request a free quote through our <a href=\"/get-quote/\">quote form</a></li> <li><strong>Step 2:</strong> Our team will send you pricing and options within 2 hours</li> <li><strong>Step 3:</strong> Approve your design proof (free design service included)</li> <li><strong>Step 4:</strong> Make payment and we start production</li> <li><strong>Step 5:</strong> Receive your order in 10-17 days</li> </ul> <p>You can also call us at <a href=\"tel:5033580443\">(503) 358-0443</a> to speak with a packaging specialist.</p>"
  },
  {
    "question": "What are your prices?",
    "answer": "<p>Pricing depends on several factors:</p> <ul> <li>Material type (Kraft, Cardboard, Corrugated, Plastic)</li> <li>Order quantity (volume discounts available)</li> <li>Size and dimensions</li> <li>Printing options (colors, coatings)</li> <li>Customization complexity</li> </ul> <p><strong>Starting prices:</strong></p> <ul> <li>Kraft Paper (250gsm): $0.70/unit</li> <li>White Cardboard (300gsm): $0.75/unit</li> <li>Corrugated (350gsm): $0.85/unit</li> <li>Plastic (PP): $0.95/unit</li> </ul> <p>Request a <a href=\"/get-quote/\">free quote</a> for exact pricing based on your needs.</p>"
  },
  {
    "question": "Do you offer samples?",
    "answer": "<p><strong>Yes!</strong> We offer sample packs so you can feel the quality before ordering.</p> <p><strong>Sample options:</strong></p> <ul> <li><strong>Blank Samples:</strong> FREE - Unprinted samples in each material</li> <li><strong>Pre-Printed Samples:</strong> $25 - Samples with generic designs</li> <li><strong>Custom Sample Run:</strong> From $50 - Small batch with your design (minimum 10 units)</li> </ul> <div class=\"hdt-faq-highlight\"> <strong>Sample Credit:</strong> If you order within 30 days, we'll credit your sample cost toward your first order! </div>"
  },
  {
    "question": "Can I order different sizes in one order?",
    "answer": "<p>Yes, you can order multiple sizes in a single order! The minimum quantity applies to the total order, not each individual size.</p> <p><strong>For example:</strong></p> <ul> <li>50 units of Small (6\")</li> <li>30 units of Medium (8\")</li> <li>20 units of Large (10\")</li> <li>Total: 100 units ✓</li> </ul> <p>Each size may have slightly different pricing based on material usage.</p>"
  },
  {
    "question": "Are there any setup fees?",
    "answer": "<p><strong>No setup fees!</strong> We believe in transparent pricing.</p> <p><strong>What's included at no extra cost:</strong></p> <ul> <li>Free design service</li> <li>Free digital proofs</li> <li>Free revisions (up to 3)</li> <li>No plate charges</li> <li>No die-cut fees for standard sizes</li> </ul> <p>You pay only for the trays themselves - no hidden fees!</p>"
  },
  {
    "question": "Do you offer rush orders?",
    "answer": "<p><strong>Yes!</strong> We offer expedited production for urgent orders.</p> <p><strong>Rush options:</strong></p> <ul> <li><strong>Standard:</strong> 7-10 business days</li> <li><strong>Rush:</strong> 5-7 business days (+20% fee)</li> <li><strong>Super Rush:</strong> 3-5 business days (+40% fee)</li> </ul> <p>Rush production is subject to availability. Contact us at <a href=\"tel:5033580443\">(503) 358-0443</a> to check if rush service is available for your order.</p>"
  },
  {
    "question": "Can I reorder the same design?",
    "answer": "<p><strong>Absolutely!</strong> Reordering is quick and easy.</p> <p>We keep your design files on record for 2 years, so you can reorder anytime without going through the design process again.</p> <p><strong>Benefits of reordering:</strong></p> <ul> <li>Faster turnaround (no design approval needed)</li> <li>Consistent branding across all orders</li> <li>Same great pricing (or better with volume discounts)</li> </ul> <p>Simply mention your previous order number when requesting a quote.</p>"
  },
  {
    "question": "Can I customize the trays with my logo?",
    "answer": "<p><strong>Yes!</strong> Full customization is included with every order at no extra cost.</p> <p><strong>What you can customize:</strong></p> <ul> <li>Your logo (any size, any position)</li> <li>Brand colors (Pantone color matching available)</li> <li>Custom text and messaging</li> <li>Graphics and illustrations</li> <li>QR codes and website URLs</li> <li>Social media handles</li> </ul> <p>Our design team will work with you to create the perfect design for your brand.</p>"
  },
  {
    "question": "Do you offer free design services?",
    "answer": "<p><strong>Yes! 100% FREE design service</strong> with every order.</p> <p><strong>What's included:</strong></p> <ul> <li>Professional graphic designers</li> <li>Unlimited design concepts</li> <li>Up to 3 free revisions</li> <li>Digital proof before production</li> <li>24-48 hour turnaround</li> </ul> <p>You can also provide your own design files in PDF, AI, EPS, or PSD format if you prefer.</p>"
  },
  {
    "question": "What file formats do you accept?",
    "answer": "<p>We accept all major design file formats:</p> <ul> <li><strong>Vector files (preferred):</strong> AI, EPS, PDF, SVG</li> <li><strong>Raster files:</strong> PSD, PNG, JPG (high resolution 300 DPI)</li> <li><strong>Logo files:</strong> Any format, we'll convert to print-ready</li> </ul> <p><strong>Don't have design files?</strong> No problem! Send us your logo in any format (even a photo of your business card) and we'll recreate it professionally.</p>"
  },
  {
    "question": "How many colors can I use?",
    "answer": "<p><strong>Unlimited colors!</strong> We use full-color CMYK printing at no additional cost.</p> <p><strong>Printing options:</strong></p> <ul> <li><strong>CMYK:</strong> Full-color process (most common)</li> <li><strong>Pantone:</strong> Spot color matching for exact brand colors</li> <li><strong>White ink:</strong> Available for dark-colored materials</li> <li><strong>Metallic:</strong> Gold and silver foil options available</li> </ul> <p>There's no limit to creativity - use as many colors as your design needs!</p>"
  },
  {
    "question": "Can I print on both sides?",
    "answer": "<p><strong>Yes!</strong> You can print on the inside, outside, or both sides of your trays.</p> <p><strong>Popular printing options:</strong></p> <ul> <li><strong>Outside only:</strong> Most common, best for branding</li> <li><strong>Inside only:</strong> Visible when filled with food</li> <li><strong>Both sides:</strong> Maximum brand exposure</li> </ul> <p>Printing on both sides may have a small additional cost depending on the design complexity.</p>"
  },
  {
    "question": "What coating options are available?",
    "answer": "<p>We offer three coating finishes:</p> <ul> <li><strong>Matte:</strong> Smooth, non-reflective finish (most popular)</li> <li><strong>Gloss:</strong> Shiny, vibrant finish that makes colors pop</li> <li><strong>Spot UV:</strong> Selective gloss areas for premium look</li> </ul> <p>All coatings provide:</p> <ul> <li>Grease resistance</li> <li>Water resistance</li> <li>Scratch protection</li> <li>Enhanced durability</li> </ul>"
  },
  {
    "question": "Can I order custom sizes?",
    "answer": "<p><strong>Absolutely!</strong> We offer fully custom sizes to fit your specific needs.</p> <p><strong>Standard sizes:</strong></p> <ul> <li>Small: 6\" × 2\" × 1\"</li> <li>Medium: 8\" × 2.5\" × 1.5\"</li> <li>Large: 10\" × 3\" × 2\"</li> <li>Extra Large: 12\" × 3.5\" × 2.5\"</li> </ul> <p><strong>Custom sizing:</strong></p> <ul> <li>Any length from 6\" to 12\"</li> <li>Custom width and depth options</li> <li>Unique shapes and die-cuts available</li> <li>Minimum order: 500 units for fully custom sizes</li> </ul>"
  },
  {
    "question": "How long does production take?",
    "answer": "<p><strong>Standard production time: 7-10 business days</strong> after design approval.</p> <p><strong>Complete timeline:</strong></p> <ul> <li>Quote & consultation: Same day</li> <li>Design & proof: 24-48 hours</li> <li>Production: 7-10 business days</li> <li>Shipping: 3-7 business days</li> <li><strong>Total: 10-17 business days</strong> from order to delivery</li> </ul> <p>Rush production available for 5-7 day or 3-5 day turnaround.</p>"
  },
  {
    "question": "What are the shipping costs?",
    "answer": "<p>Shipping costs vary based on order size and destination.</p> <p><strong>Estimated shipping costs:</strong></p> <ul> <li>100-500 units: $50-$150</li> <li>500-1,000 units: $100-$200</li> <li>1,000-5,000 units: $150-$300</li> <li><strong>5,000+ units: FREE SHIPPING</strong> (within USA)</li> </ul> <p>Exact shipping cost will be included in your quote.</p>"
  },
  {
    "question": "Do you ship internationally?",
    "answer": "<p><strong>Yes!</strong> We ship worldwide to over 50 countries.</p> <p><strong>International shipping times:</strong></p> <ul> <li><strong>Canada:</strong> 3-5 business days</li> <li><strong>UK & Europe:</strong> 5-7 business days</li> <li><strong>Australia:</strong> 7-10 business days</li> <li><strong>Asia:</strong> 7-10 business days</li> <li><strong>Other regions:</strong> 10-15 business days</li> </ul> <p>Customs duties and import taxes are the responsibility of the buyer.</p>"
  },
  {
    "question": "Can I track my order?",
    "answer": "<p><strong>Yes!</strong> All orders include tracking.</p> <p>You'll receive:</p> <ul> <li>Order confirmation email immediately</li> <li>Design proof within 24-48 hours</li> <li>Production start notification</li> <li>Shipping notification with tracking number</li> <li>Delivery confirmation</li> </ul> <p>Track your order 24/7 at any time using your tracking number.</p>"
  },
  {
    "question": "What if my order is damaged during shipping?",
    "answer": "<p>We pack all orders securely, but if damage occurs:</p> <ul> <li><strong>Report damage within 48 hours</strong> of delivery</li> <li>Provide photos of the damage</li> <li>We'll file a claim with the carrier</li> <li>We'll send replacement items at no cost</li> </ul> <div class=\"hdt-faq-highlight\"> <strong>100% Satisfaction Guarantee:</strong> If any items are damaged, we'll replace them free of charge. </div>"
  },
  {
    "question": "Do you offer expedited shipping?",
    "answer": "<p><strong>Yes!</strong> We offer several shipping speed options:</p> <ul> <li><strong>Standard:</strong> 5-7 business days (included)</li> <li><strong>Express:</strong> 2-3 business days (+$50-$150)</li> <li><strong>Overnight:</strong> 1-2 business days (+$200-$400)</li> </ul> <p>Expedited shipping costs depend on order size and destination. Contact us for exact pricing.</p>"
  },
  {
    "question": "What payment methods do you accept?",
    "answer": "<p>We accept all major payment methods:</p> <p><strong>Credit & Debit Cards:</strong></p> <ul> <li>Visa, Mastercard, American Express, Discover</li> </ul> <p><strong>Digital Payments:</strong></p> <ul> <li>PayPal, Apple Pay, Google Pay</li> </ul> <p><strong>Business Payments:</strong></p> <ul> <li>Bank transfers (ACH/Wire)</li> <li>Purchase orders (for established businesses)</li> <li>Net 30 terms (available for qualified businesses)</li> </ul> <div class=\"hdt-faq-highlight\"> <strong>Secure Payment:</strong> All transactions are encrypted with SSL security </div>"
  },
  {
    "question": "When do I need to pay?",
    "answer": "<p><strong>Payment is required before production begins.</strong></p> <p><strong>Payment schedule:</strong></p> <ul> <li>Receive quote (no payment required)</li> <li>Approve design proof (no payment required)</li> <li><strong>Make payment → Production starts</strong></li> </ul> <p><strong>For established businesses:</strong></p> <ul> <li>50% deposit to start production</li> <li>50% balance before shipping</li> <li>Net 30 terms available (approval required)</li> </ul>"
  },
  {
    "question": "What is your return policy?",
    "answer": "<p>We stand behind our products with a <strong>100% Satisfaction Guarantee</strong>.</p> <p><strong>Quality Issues:</strong></p> <ul> <li>Manufacturing defects → Free replacement</li> <li>Printing errors → Free reprint</li> <li>Quality issues → Full refund or replacement</li> <li>Claims must be made within 30 days</li> </ul> <p><strong>Design Errors:</strong></p> <ul> <li>We require design approval before production</li> <li>If we make an error (not matching proof) → Free reprint</li> </ul> <div class=\"hdt-faq-highlight\"> <strong>Important:</strong> Custom printed products cannot be returned due to change of mind, as they are made specifically for your business. </div>"
  },
  {
    "question": "Do you offer refunds?",
    "answer": "<p><strong>Yes</strong>, under certain conditions:</p> <p><strong>Full refund if:</strong></p> <ul> <li>We make a production error</li> <li>Quality doesn't meet our standards</li> <li>Items are defective or damaged</li> <li>Order hasn't started production yet</li> </ul> <p><strong>No refund for:</strong></p> <ul> <li>Change of mind after production starts</li> <li>Approved designs (even if you later change your mind)</li> <li>Incorrect information provided by customer</li> </ul> <p>For full details, see our <a href=\"/terms-conditions/\">Returns & Refunds Policy</a>.</p>"
  },
  {
    "question": "Is my payment information secure?",
    "answer": "<p><strong>Absolutely!</strong> We take security very seriously.</p> <p><strong>Security measures:</strong></p> <ul> <li>SSL encryption on all pages</li> <li>PCI DSS compliant payment processing</li> <li>Secure payment gateway</li> <li>No credit card data stored on our servers</li> <li>Fraud detection systems</li> </ul> <p>Your financial information is safe and will never be shared with third parties.</p>"
  }
];
